#!/usr/bin/env bash
# Simulate a synthetic astronomical field with Stuff + SkyMaker, then run
# SExtractor on it. Demonstrates the classic AstrOmatic simulation workflow
# available in the improc image:
#
#   Stuff  ->  galaxy catalog (positions, magnitudes, morphologies)
#   SkyMaker -> simulated FITS image from that catalog + procedural stars
#   SExtractor -> source catalog extracted from the simulated image
#
# Run inside the improc container:
#   bash simulate_field.sh            (defaults: 2048x2048, sdss/r)
#   FIELD_SIZE=1024,1024 bash simulate_field.sh
#
# Outputs (in ./sim):
#   sim.list     catalog of galaxies generated by Stuff
#   sim_r.fits   2048x2048 simulated image (with background + noise)
#   sim_r.list   catalog of the sources SkyMaker actually rendered
#   sim_r.cat    catalog of sources SExtractor detected
#   sky.conf, stuff.conf   generated configuration files

set -euo pipefail

# --- Tunables (override via environment) ------------------------------------
FIELD_SIZE="${FIELD_SIZE:-2048,2048}"   # pixels, matches PIXEL_SIZE=0.2" -> 6.8'
PASSBAND="${PASSBAND:-sdss/r}"          # Stuff passband (see /usr/local/share/stuff/data/filters)
MAG_MIN="${MAG_MIN:-16.0}"              # faintest Stuff galaxies
MAG_MAX="${MAG_MAX:-24.0}"              # brightest Stuff galaxies
SEEING="${SEEING:-1.2}"                 # FWHM seeing (arcsec)
OUTDIR="${OUTDIR:-sim}"

mkdir -p "$OUTDIR"
cd "$OUTDIR"

echo ">> generating Stuff configuration"
stuff -d > stuff.conf
sed -i \
  -e "s|^CATALOG_NAME.*|CATALOG_NAME    sim.list|" \
  -e "s|^COORD_TYPE.*|COORD_TYPE      PIXEL|" \
  -e "s|^FIELD_SIZE.*|FIELD_SIZE      ${FIELD_SIZE}|" \
  -e "s|^PASSBAND_OBS.*|PASSBAND_OBS    ${PASSBAND}|" \
  -e "s|^MAG_LIMITS.*|MAG_LIMITS      ${MAG_MIN},${MAG_MAX}|" \
  stuff.conf

echo ">> Stuff: generating galaxy catalog"
stuff -c stuff.conf >/dev/null 2>&1
n_gal=$(grep -vc "^#" sim.list || true)
echo "   ${n_gal} galaxies written to sim.list"

echo ">> generating SkyMaker configuration"
sky -d > sky.conf
sed -i \
  -e "s|^IMAGE_SIZE.*|IMAGE_SIZE      ${FIELD_SIZE}|" \
  -e "s|^IMAGE_NAME.*|IMAGE_NAME      sim_r.fits|" \
  -e "s|^MAG_LIMITS.*|MAG_LIMITS      14.0,26.0|" \
  -e "s|^SEEING_FWHM.*|SEEING_FWHM     ${SEEING}|" \
  sky.conf

echo ">> SkyMaker: rendering simulated image"
sky sim.list -c sky.conf 2>&1 | grep -E "sources added" || true

echo ">> SExtractor: extracting sources from the simulated image"
# SExtractor looks for default.param in the working directory; use the
# config files shipped with the image.
cp /usr/share/source-extractor/default.sex /usr/share/source-extractor/default.param /usr/share/source-extractor/default.conv .
sextractor sim_r.fits -c default.sex -CATALOG_NAME sim_r.cat 2>&1 | grep -E "All done" || true
n_det=$(grep -vc "^#" sim_r.cat || true)

echo
echo "Done. ${n_det} sources detected in ${n_gal}-galaxy simulated field:"
ls -lh sim_r.fits sim.list sim_r.list sim_r.cat
